autodetect does not work for overlay fs, set autodetect to failed
archlinux/mkinitcpio pull request #106
Opened 2022-05-30 12:44 UTC by brandsimon

It is possible to get the upper/lower directories for overlay fs:
```
findmnt -n '/' | sed -e 's/ /\n/g' -e 's/,/\n/g' | sed -e '/^\(lower\|upper\)dir=/!d'
```
Since the root was switched to the overlay mount point, these mountpoints usually don't exist. I don't know a solution to detect the filesystemtypes of these "old" mountpoints, so fallback to autodetect failed.
If there is a better solution, I am happy to adapt the PR.

2022-07-07 22:48 UTC, brandsimon commented
Is there anything missing in this PR?
This can be reproduced with the project `verify-squash-root` [0] [1], where I found the problem.

[0] https://github.com/brandsimon/verify-squash-root/
[1] https://aur.archlinux.org/packages/verify-squash-root

2022-10-22 14:54 UTC, nl6720 requested changes

2022-10-22 14:54 UTC, nl6720 commented on install/autodetect
> +        if [ "${rootfstype}" = "overlay" ]; then
```suggestion
        if [[ "${rootfstype}" == "overlay" ]]; then
```

2022-10-22 23:24 UTC, brandsimon commented on install/autodetect
> +        if [ "${rootfstype}" = "overlay" ]; then
@nl6720 Done

2022-10-23 17:19 UTC, Foxboron approved these changes

2022-10-24 14:57 UTC, nl6720 approved these changes

2022-10-24 15:02 UTC, merged