ensure consistency for the generated image
archlinux/mkinitcpio pull request #124
Opened 2022-10-22 12:19 UTC by christian-heusel

This just applies the proposed fix from @Artefact2 in the linked issue.
Should we make this behaviour more configurable as it increases the space requirements, which could be a breaking change for people with full `/boot`?

fixes https://github.com/archlinux/mkinitcpio/issues/64

2022-10-22 12:20 UTC, christian-heusel commented
I could also add Co-Authorship for the person that opened the issue if wanted!

2022-10-22 12:21 UTC, Artefact2 commented
It's a trivial fix, I don't mind. Happy to see it fixed in mainline :)

2022-10-22 12:22 UTC, Foxboron approved these changes

2022-10-22 12:25 UTC, nl6720 commented
> it increases the space requirements

IMHO this is quite a big issue. People with 100 MiB `/boot` already exceed space requirements frequently enough.

The [suggested `/boot` size in the wiki](https://wiki.archlinux.org/title/Partitioning#/boot) would need updating too.

2022-10-22 12:36 UTC, christian-heusel commented
> it increases the space requirements

It increases the space requirements by `max(img_filesizes)` as the rename is happening after each image, so we get to a new needed minimum amount of `sum(img_filesizes) + max(img_filesizes)`.
For the two machines i am testing this with this means the increase is +34M because of the size of `initramfs-linux-fallback.img`.

How big can these get?

2022-10-22 12:41 UTC, nl6720 commented
Generally, the more crap you add, the bigger it gets.
I myself have a 49 MiB `initramfs-linux-fallback.img`, but I'm using 
```bash
COMPRESSION="xz"
COMPRESSION_OPTIONS=(-9e)
```
With the default compressions options, it's 66 MiB for me.

2022-10-22 12:43 UTC, Artefact2 commented
The initramfses can get quite large, especially in NVIDIA users that want early kms (80-ish megs last time I checked).

2022-10-22 12:44 UTC, nl6720 requested changes
I think there should be a fallback to truncating in case there's not enough free space.

2022-10-22 13:50 UTC, nl6720 requested changes

2022-10-22 13:50 UTC, nl6720 commented on mkinitcpio
> +        fi
```suggestion
        (( $((curr_size*2)) < space_left_on_device )) && compressout="$out".tmp
```

2022-10-22 13:50 UTC, nl6720 commented on mkinitcpio
> +        space_left_on_device=$(($(stat -f --format="%a*%S" $out)))
```suggestion
        curr_size="$(stat --format="%s" "$out")"
        space_left_on_device="$(($(stat -f --format="%a*%S" "$out")))"
```

2022-10-22 13:50 UTC, nl6720 commented on mkinitcpio
> +        mv -f "$compressout" "$out"
```suggestion
        sync -d -- "$compressout"
        mv -f -- "$compressout" "$out"
```

2022-10-22 13:56 UTC, nl6720 requested changes

2022-10-22 13:56 UTC, nl6720 commented on mkinitcpio
> +        if (( $(($curr_size*2)) < $space_left_on_device )); then
This probably needs to a little buffer.

2022-10-22 14:58 UTC, nl6720 commented
I'm getting:
```
==> ERROR: Image generation FAILED: find reported an error
```
The `find` in question is this one:

```bash
    find . -mindepth 1 -printf '%P\0' |
            sort -z |
            LANG=C bsdtar --uid 0 --gid 0 --null -cnf - -T - |
            LANG=C bsdtar --null -cf - --format=newc @- |
            $compress "${COMPRESSION_OPTIONS[@]}" > "$compressout"
```

Which turns into:

```bash
+ find . -mindepth 1 -printf '%P\0'
+ sort -z
+ LANG=C
+ bsdtar --uid 0 --gid 0 --null -cnf - -T -
+ xz --check=crc32 -9e
+ LANG=C
+ bsdtar --null -cf - --format=newc @-
+ [[ /boot/initramfs-linux.img != \/\b\o\o\t\/\i\n\i\t\r\a\m\f\s\-\l\i\n\u\x\.\i\m\g ]]

```

This is with a 100MiB `/boot`:

```
Filesystem     Type  Size  Used Avail Use% Mounted on
/dev/loop0     vfat   99M   81M   18M  83% /boot
```

2022-10-22 16:38 UTC, nl6720 commented
> ```
> ==> ERROR: Image generation FAILED: find reported an error
> ```

This issue is now gone.

2022-10-22 16:42 UTC, nl6720 commented
Now it's just a question of how much space to reserve. :thinking:

2022-10-22 16:48 UTC, christian-heusel commented
> Now it's just a question of how much space to reserve. thinking

Wdym? Imo we could just leave it as is and maybe emit a warning if the partition is to full 🤔 But since its just not doing a more safe upgrade I think this also could be left as-is.

> The [suggested /boot size in the wiki](https://wiki.archlinux.org/title/Partitioning#/boot) would need updating too.

With the now implemented behaviour (doing atomic rename when possible, otherwise use the current behaviour) I think one could also argue that there is no change needed in the wiki.

2022-10-22 16:50 UTC, nl6720 commented on mkinitcpio
> +        # this assumes that the new image is not more than 1 1/4x the size of the old one
```suggestion
        # this assumes that the new image is not more than 1¼ times the size of the old one
```

2022-10-22 16:52 UTC, nl6720 commented
> With the now implemented behaviour (doing atomic rename when possible, otherwise use the current behaviour) I think one could also argue that there is no change needed in the wiki.

:+1:

2022-10-22 16:55 UTC, nl6720 commented
> Wdym? Imo we could just leave it as is and maybe emit a warning if the partition is to full thinking But since its just not doing a more safe upgrade I think this also could be left as-is.

I mean, is 1¼× enough to account for the new image's potential size increase?

2022-10-22 16:58 UTC, christian-heusel commented
> I mean, is 1¼× enough to account for the new image's potential size increase?

🤷🏻‍♂️ I dont know, for my current setup this would mean 8.5MB slack for the fallback img. I think it should be enough for regular upgrades of any kind.

> maybe emit a warning if the partition is to full thinking

what do you think about this?

2022-10-22 16:58 UTC, nl6720 approved these changes

2022-10-22 17:06 UTC, nl6720 commented
It'd feel safer to additionally add some fixed (not dependent on the previous image size) amount of free space to the equation.

2022-10-22 23:21 UTC, christian-heusel commented
Re-requesting review because of the bigger changes after the initial approve 😊

2022-10-23 17:44 UTC, Foxboron commented
I need to test it so I understand how it works. It looks good to me but please squash the last 3 commits into the 2nd one, or squash everything together :)

2022-10-23 23:15 UTC, christian-heusel commented
@Foxboron commits are now squashed 👍🏻

2022-10-24 18:07 UTC, merged