Remove hexdump usage
archlinux/mkinitcpio pull request #23
Opened 2020-05-20 01:55 UTC by E5ten

lsinitcpio: Use read to get the first 6 bytes, convert them to hex, and
compare them to the hex versions of the magic bytes of each compression
format
Replace the kernel version offset determination using hexdump with dd to
skip bytes, and printf to convert the bytes to decimal

2020-05-20 09:46 UTC, falconindy commented
Why do we care about removing hexdump?

2020-05-20 15:22 UTC, E5ten commented
In terms of the lsinitcpio change, hexdump is called 6 times with separate comparisons after each call, it seems a lot simpler to me to turn that into one read, a printf, and then one case for all the comparisons. For the other change (the same one in functions and completion files), dd is already used to find the kernel version using the given offset, so since it's possible to also obtain that offset using dd, which is a POSIX command, it makes sense to me to do that, instead of using 2 different tools for finding the version.

2020-10-27 17:04 UTC, grazzolini commented
@E5ten can you rebase this?

2020-10-27 17:30 UTC, E5ten commented
@grazzolini done

2020-10-27 18:33 UTC, grazzolini commented
@E5ten thanks. I'll do some testing on this. Not sure yet if it can make to the next release, but perhaps to the next one.

2021-01-25 19:46 UTC, evelikov commented
Some food for though - `detect_filetype` is effectively* only needed for the compression stats aka:
```
Compressed with: foo
Uncompressed size: 100 (0.007 ratio)
Estimated decompression time: 100s
```
Of which the estimate is off since it compares standalone decompressor + libarchive tar handling wrt the in-kernel code. One could remove it - or the whole section all together?

*Effectively - since in every other case, `bsdtar` can be used directly to decompress fully.

2021-02-11 17:05 UTC, tlahdekorpi commented
Like hexdump, dd also does not exit with a non-zero status code when you try to read past the selected offset. Using od to read and convert the offset to a number would be a better solution.

tlahdekorpi/mkinitcpio-ag@45285b4

2022-10-30 07:56 UTC, nl6720 requested changes
This needs to be rebased after db25bf84f3d8740921bcd9035c9050b85b320a45.
And as suggested in https://github.com/archlinux/mkinitcpio/pull/23#issuecomment-777645680, changed to use `od`.

2022-11-09 23:08 UTC, klausenbusk commented
Moved to to: https://gitlab.archlinux.org/archlinux/mkinitcpio/mkinitcpio/-/merge_requests/23.

2022-11-09 23:08 UTC, closed without merging